apiVersion: v1
kind: Service
metadata:
  name: joke-deploy
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: joke-deploy
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005